#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 215

#define COMBO_TERM 100

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 240000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 5

#define SERIAL_NUMBER "G53qV/qmZDd3"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

